services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lexicondb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  cache:
    image: redis
    ports:
      - '6379:6379'
volumes:
  postgres-data:
    driver: local